global:
  scrape_interval: 30s  

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - https://ptsecurity.com  
    relabel_configs:
      - source_labels: [__param_target]
        target_label: target
      - source_labels: [__param_module]
        target_label: module
      - target_label: __address__
        replacement: blackbox_exporter:9115 
